import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from './components/SessionProvider';
import NavMenu from './components/NavMenu/NavMenu';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from './theme';
import { StyledEngineProvider } from '@mui/material/styles';
import authOptions from './api/auth/[...nextauth]/authOptions';
import { AuthSession } from './types/types';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getServerSession(authOptions)) as AuthSession;
  return (
    <html lang='en'>
      <StyledEngineProvider injectFirst>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <body className={inter.className}>
              <SessionProvider session={session}>
                <main className='bg-neutral-900'>
                  <NavMenu />
                  {children}
                </main>
              </SessionProvider>
            </body>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </StyledEngineProvider>
    </html>
  );
}
